# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Banner Section
  description: Banner Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: banner
  banner: /images/bg-banner.png
  banner_alt: banner

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id: 
    label: ID section
    type: text
  banner:
    label: Banner
    type: image
  banner_alt:
    label: Banner Alt
    type: text