# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Blog Section
  description: Blog Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title_highlight: NEWS 
  title: '& BLOGS'
  button: 
    text: View more
    url: /blog

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id: 
    label: ID section
    type: text
  title_highlight: 
    label: Title Highlight
    type: text
  title: 
    label: Title
    type: text
  button.url:
    label: Button URL
    type: text
  button.text:
    label: Button Text
    type: text
