# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Gallery Section
  description: Gallery Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: gallery
  gallery:
    - image: /images/gallery-1.png
      image_alt: gallery 1
      tag: Fruits & Veges
    - image: /images/gallery-2.png
      image_alt: gallery 1
      tag: Breakfast & Cereal
    - image: /images/gallery-2.png
      image_alt: gallery 1
      tag: Bread & Pastries
    - image: /images/gallery-2.png
      image_alt: gallery 1
      tag: Beer, Wine & Spirits
    - image: /images/gallery-2.png
      image_alt: gallery 1
      tag: Seeds & Nuts

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id: 
    label: ID section
    type: text
  gallery[*].image:
    label: Image
    type: image
  gallery[*].image_alt:
    label: Image Alt
    type: text